"""Criando BD - Atividades

Revision ID: 4870c49cff04
Revises: b1a7264c156f
Create Date: 2022-07-12 17:58:50.431576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4870c49cff04'
down_revision = 'b1a7264c156f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_atividades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('dataDeCriacao', sa.Date(), nullable=False),
    sa.Column('dataDeEdicao', sa.Date(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['tbl_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_atividades')
    # ### end Alembic commands ###
