"""Atualizando BD

Revision ID: 6b70dc44c809
Revises: 4870c49cff04
Create Date: 2022-07-13 09:31:28.002798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b70dc44c809'
down_revision = '4870c49cff04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
