"""Adicionando user 2

Revision ID: 8eada661fd80
Revises: b3e3c265da73
Create Date: 2022-07-31 21:00:13.047751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eada661fd80'
down_revision = 'b3e3c265da73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
