"""Adicionando user 3

Revision ID: b0fd21deae11
Revises: 8eada661fd80
Create Date: 2022-07-31 21:14:03.541968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fd21deae11'
down_revision = '8eada661fd80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
