"""Adicionando user

Revision ID: b3e3c265da73
Revises: f301d3d648c2
Create Date: 2022-07-31 20:52:04.476112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e3c265da73'
down_revision = 'f301d3d648c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
