"""Primeiro Upload

Revision ID: c4afae05824d
Revises: 5158b9c66a1a
Create Date: 2022-07-12 17:47:57.641577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4afae05824d'
down_revision = '5158b9c66a1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
