"""Alterando Tipo Data

Revision ID: cb43bbffcb02
Revises: 6b70dc44c809
Create Date: 2022-07-15 12:06:53.475749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb43bbffcb02'
down_revision = '6b70dc44c809'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
