"""Adicionando usuario

Revision ID: f301d3d648c2
Revises: c8fb756c948a
Create Date: 2022-07-31 20:42:16.429726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f301d3d648c2'
down_revision = 'c8fb756c948a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
